CREATE TABLE IF NOT EXISTS "Tasks" (
                                       "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                       "Title" character varying(200) NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "DueDate" timestamp with time zone,
                            "IsCompleted" boolean NOT NULL,
                            "Priority" integer NOT NULL,
                            CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id")
    );

CREATE INDEX IF NOT EXISTS "IX_Tasks_IsCompleted" ON "Tasks" ("IsCompleted");